# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3d685edb5b98f91fa4d698f0e6683b741e85fb59236e9f5d063a0d9ae09f008441d666893b351a1b852befd802a5bf2b4168e52ca3c3874d804cb815691ed01

test:
  secret_key_base: 81af0c98f43159c159504112b2e3e035714d7691bf09804e26b0fe10fb4fd90c3d48fe77df36afeb1f12d4120b1152039007aed4c31821dcadd4533c06965bcc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
